services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  app:
    build: .
    container_name: rag_app
    ports:
      - "8000:8000"
    volumes:
      - ./pdfs:/app/pdfs
      - ./logs:/app/logs
    depends_on:
      qdrant:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    restart: unless-stopped
